### ISSUE TITLE
Synergy API Documentation

### ISSUE THREAD

**Issue by advait** [yungsters/node-somfy-synergy#1]
Hello! Do you know if there's public documentation available for the Somfy Synergy API? I can't seem to find anything on somfysystems.com.

I'm interested in knowing whether you can get information from the MyLink as opposed to sending it passive commands.

**Comment by yungsters** [comment]
I think documentation for Somfy’s Synergy API is only available to authorized dealers or something.

I learned what I used in this repository by studying the image on this page (and poking around): https://www.somfysystems.com/somfy-synergy-api

I recall also finding some tips via Google.

AFAIK, the Somfy motors only supper one-way communication. So I don’t think there any way to read, for example, the current position of the motor.

**Comment by adriweb** [comment]
> AFAIK, the Somfy motors only supper one-way communication. So I don’t think there any way to read, for example, the current position of the motor.

It depends on the protocol they use, but for RTS, yes indeed.
